### ISSUE TITLE
Fails to build with node.js v12.0.0 release

### ISSUE THREAD

**Issue by mdouglass** [grpc/grpc-node#834]
### Problem description
```
../ext/channel.cc:292:56: error: too few arguments to function call, expected 2, have 1
  int try_to_connect = (int)info[0]->Equals(Nan::True());
                            ~~~~~~~~~~~~~~~            ^
/Users/mdouglass/.node-gyp/12.0.0/include/node/v8.h:2572:3: note: 'Equals' declared here
  V8_WARN_UNUSED_RESULT Maybe<bool> Equals(Local<Context> context,
  ^
/Users/mdouglass/.node-gyp/12.0.0/include/node/v8config.h:347:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
```

### Reproduction steps
```bash
npm init
npm install grpc@latest
```

### Environment
 - macOS 10.14.4
 - node.js v12.0.0 installed via macOS installer from nodejs.org
 - gRPC 1.20.0

### Additional context
Attached log files
[2019-04-23T22_09_12_791Z-debug.log](https://github.com/grpc/grpc-node/files/3109788/2019-04-23T22_09_12_791Z-debug.log)
[console.log](https://github.com/grpc/grpc-node/files/3109789/npm-debug.log)

**Comment by sangaman** [comment]
Same issue on Ubuntu 19.04, node 12.0.0 installed with nvm, grpc 1.18.0.

**Comment by nicolasnoble** [comment]
We are working on getting 1.20.1 out with node 12 support, stay tuned.

**Comment by murgatroid99** [comment]
`grpc@1.20.1` is now out with Node 12 support.

**Comment by murgatroid99** [comment]
Update: we had to unpublish 1.20.1 because it broke the TypeScript types. 1.20.2 will be out soon.

**Comment by aaaguirrep** [comment]
I have the next issue with nodejs 12.0 when it runs npm rebuild, is it the same issue?

```
3585 error code ELIFECYCLE
3586 error errno 1
3587 error grpc@1.20.0 install: `node-pre-gyp install --fallback-to-build --library=static_library`
3587 error Exit status 1
3588 error Failed at the grpc@1.20.0 install script.
3588 error This is probably not a problem with npm. There is likely additional logging output above.
3589 verbose exit [ 1, true ]
```

**Comment by nicolasnoble** [comment]
@aaaguirrep you haven't provided nearly enough information for us to tell if that's the case, but it most likely is, since it's 100% impossible to use grpc with node 12 at the moment.

**Comment by murgatroid99** [comment]
version 1.20.2 is now out.

**Comment by aaaguirrep** [comment]
What is the process to upgrade gprc? I not see the new release in the repositorie.

**Comment by sangaman** [comment]
> What is the process to upgrade gprc?

`npm install grpc@1.20.2` should work.

**Comment by aaaguirrep** [comment]
It worked, I dont see errors running `npm rebuild`

**Comment by nicolasnoble** [comment]
Closing as resolved.

**Comment by aaaguirrep** [comment]
does it work for yarn? I am having an issue upgrading or installing the new release but i am not sure if the issue is with grpc or other dependencies.

**Comment by nicolasnoble** [comment]
Our yarn support always has been best effort. We don't officially support it.

**Comment by cekvenich** [comment]
FYI this is used in FireBase and they still ship the old version that does not work w/ Node v12.
I use FireBase and that is why I'm here. Now I'm monkey patching package.json to replace what FireBase ships.

**Comment by nicolasnoble** [comment]
I would suggest filling an issue with firebase then.

**Comment by cekvenich** [comment]
I would love to - but I don't know how/where. I went on their website and filed a comment and sent a message to their group. The stack trace shows that the version they released *TODAY* is using the older version of grpc.  I use 40 npm modules at least 10 are native and the only one w/ that does not work is Google Firebase. And no way to flag them or do PR.

**Comment by nicolasnoble** [comment]
https://github.com/firebase/firebase-js-sdk

**Comment by cekvenich** [comment]
THANK YOU.

**Comment by aaaguirrep** [comment]
I am also using firebase in my project and  it shows the issue. I thought that issue was related to yarn.

**Comment by cekvenich** [comment]
@aaaguirrep please upvote https://github.com/firebase/firebase-js-sdk/issues/1738

**Comment by EngAhmedShehatah** [comment]
npm ERR! grpc@1.20.0 install: `node-pre-gyp install --fallback-to-build --library=static_library`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the grpc@1.20.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

I'm trying to use ( npm install ) to install a project node_modules
node -v = v12.4.0
npm -v = 6.9.0
angular 8

**Comment by pointer2null** [comment]
Same issue:

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! grpc@1.20.2 install: `node-pre-gyp install --fallback-to-build --library=static_library`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the grpc@1.20.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm -v
6.9.0
node -v
v10.16.0
(fedora 29)

**Comment by murgatroid99** [comment]
Please post the entire error message, or at least the first several lines.

**Comment by pointer2null** [comment]
This issue seemed to be closed so opened #922

**Comment by EngAhmedShehatah** [comment]
> grpc@1.20.0 install /home/ahmed/Documents/alghanim-phase2-frontend/node_modules/grpc
> node-pre-gyp install --fallback-to-build --library=static_library

node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp WARN Tried to download(404): https://node-precompiled-binaries.grpc.io/grpc/v1.20.0/node-v72-linux-x64-glibc.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for grpc@1.20.0 and node@12.4.0 (node-v72 ABI, glibc) (falling back to source compile with node-gyp) 
gyp ERR! build error 
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:13:12)
gyp ERR! stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:68:19)
gyp ERR! stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:165:21)
gyp ERR! System Linux 4.18.0-22-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--library=static_library" "--module=/home/ahmed/Documents/alghanim-phase2-frontend/node_modules/grpc/src/node/extension_binary/node-v72-linux-x64-glibc/grpc_node.node" "--module_name=grpc_node" "--module_path=/home/ahmed/Documents/alghanim-phase2-frontend/node_modules/grpc/src/node/extension_binary/node-v72-linux-x64-glibc" "--napi_version=4" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v72"
gyp ERR! cwd /home/ahmed/Documents/alghanim-phase2-frontend/node_modules/grpc
gyp ERR! node -v v12.4.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --library=static_library --module=/home/ahmed/Documents/alghanim-phase2-frontend/node_modules/grpc/src/node/extension_binary/node-v72-linux-x64-glibc/grpc_node.node --module_name=grpc_node --module_path=/home/ahmed/Documents/alghanim-phase2-frontend/node_modules/grpc/src/node/extension_binary/node-v72-linux-x64-glibc --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/ahmed/Documents/alghanim-phase2-frontend/node_modules/grpc/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:200:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
node-pre-gyp ERR! System Linux 4.18.0-22-generic
node-pre-gyp ERR! command "/usr/bin/node" "/home/ahmed/Documents/alghanim-phase2-frontend/node_modules/grpc/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"
node-pre-gyp ERR! cwd /home/ahmed/Documents/alghanim-phase2-frontend/node_modules/grpc
node-pre-gyp ERR! node -v v12.4.0
node-pre-gyp ERR! node-pre-gyp -v v0.12.0
node-pre-gyp ERR! not ok 
Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --library=static_library --module=/home/ahmed/Documents/alghanim-phase2-frontend/node_modules/grpc/src/node/extension_binary/node-v72-linux-x64-glibc/grpc_node.node --module_name=grpc_node --module_path=/home/ahmed/Documents/alghanim-phase2-frontend/node_modules/grpc/src/node/extension_binary/node-v72-linux-x64-glibc --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
npm WARN @ng-bootstrap/ng-bootstrap@4.2.1 requires a peer of rxjs@^6.3.0 but none is installed. You must install peer dependencies yourself.
npm WARN @ngtools/webpack@6.0.8 requires a peer of typescript@~2.4.0 || ~2.5.0 || ~2.6.0 || ~2.7.0 but none is installed. You must install peer dependencies yourself.
npm WARN angular-in-memory-web-api@0.6.1 requires a peer of @angular/common@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN angular-in-memory-web-api@0.6.1 requires a peer of @angular/core@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN angular-in-memory-web-api@0.6.1 requires a peer of @angular/http@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN angular2-csv@0.2.9 requires a peer of @angular/common@^6.0.0-rc.0 || ^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN angular2-csv@0.2.9 requires a peer of @angular/core@^6.0.0-rc.0 || ^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN The package @angular/compiler is included as both a dev and production dependency.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/webpack-dev-server/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/watchpack/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/rijs.resdir/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/karma/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.0.7 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.0.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/@schematics/update/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/@schematics/angular/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/@angular/compiler-cli/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/@angular/cli/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/@angular-devkit/schematics/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/@angular-devkit/core/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! grpc@1.20.0 install: `node-pre-gyp install --fallback-to-build --library=static_library`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the grpc@1.20.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by EngAhmedShehatah** [comment]
Dear Grpc/Grpc-Node Team,

Sorry for the late reply. I have commented with the full error text from
the very beginning.
If you need info about my system or any other info just let me know.

Thanks in advance and I am looking forward to hearing from you.

Best Regards,
*Ahmed Mohammed Shehatah*
Front-End Web Developer
Email: engahmedshehatah@gmail.com
Mobile: +201005363688

**Comment by murgatroid99** [comment]
You are using a version of the grpc library that does not support Node 12. Please use either a newer version of grpc or an older version of Node.

**Comment by tdeleanu** [comment]
Same issue.
Had to upgrade to "grpc": "^1.20.2".

**Comment by AHPanna** [comment]
i just downgrade node using (10.9.0), and fixed for now.

**Comment by mybcplus** [comment]
> I have the next issue with nodejs 12.0 when it runs npm rebuild, is it the same issue?
> 
> ```
> 3585 error code ELIFECYCLE
> 3586 error errno 1
> 3587 error grpc@1.20.0 install: `node-pre-gyp install --fallback-to-build --library=static_library`
> 3587 error Exit status 1
> 3588 error Failed at the grpc@1.20.0 install script.
> 3588 error This is probably not a problem with npm. There is likely additional logging output above.
> 3589 verbose exit [ 1, true ]
> ```

how you solve it

**Comment by pointer2null** [comment]
see https://github.com/grpc/grpc-node/issues/922 for workaround

**Comment by safciplak** [comment]
> > What is the process to upgrade gprc?
> 
> `npm install grpc@1.20.2` should work.

Thanks it's working

**Comment by Vichet97** [comment]
can you tell me the command to list all development environment ?
Is it react-native info ?
