### PR TITLE
grpc-js: Timer ref and unref might not exist

### LINKED ISSUE #1708: Timer issue when updating grpc-js from 1.2.6 to 1.2.7
### Problem description
When updating from grpc-js 1.2.6 to 1.27 (and greater - I tried 1.2.8, .9, and .10 as well), there is an issue that arises at least when being used in electronjs, I think it has to do with setTimeout/setInterval using the NodeJS version or browser version, some kind of incompatibility there.

It causes electron's preload.js to fail to load due to the following error with BackoffTimerout.unref:
```
TypeError: this.timerId.unref is not a function
    at BackoffTimeout.unref (VM167 C:\Users\keith…ckoff-timeout.js:99)
    at new ResolvingLoadBalancer (VM162 C:\Users\keith…oad-balancer.js:159)
    at new ChannelImplementation (VM131 C:\Users\keith…\src\channel.js:123)
    at new Client (VM188 C:\Users\keith…ld\src\client.js:58)
    at new ServiceClientImpl (VM191 C:\Users\keith…c\make-client.js:58)
    at new CoreServices (VM123 C:\Users\keith…CoreServices.js:109)
    at Object.<anonymous> (VM87 C:\Users\keithl…ctron\preload.js:62)
    at Object.<anonymous> (VM87 C:\Users\keithl…tron\preload.js:105)
    at Module._compile (VM42 loader.js:1152)
    at Object.Module._extensions..js (VM42 loader.js:1173)
```

### Reproduction steps
I am building this off of secure-electron-template with the addition of gRPC with the following dependencies:
```
  "devDependencies": {
    "@grpc/proto-loader": "^0.5.6",
    "@types/google-protobuf": "^3.7.4",
    "@types/node": "^14.14.31",
    "cross-env": "^7.0.3",
    "grpc-tools": "1.10.0",
    "grpc_tools_node_protoc_ts": "5.1.3",
    "tslint": "^6.1.3",
    "typescript": "^4.2.2"
  },
  "dependencies": {
    "@grpc/grpc-js": "1.2.7",
    "google-protobuf": "3.15.5"
  }

```
See: https://github.com/reZach/secure-electron-template

### Environment
 - OS name, version and architecture: [e.g. Linux Ubuntu 18.04 amd64]
Windows 10 x64
 - Node version [e.g. 8.10.0]
v14.16.0
 - Node installation method [e.g. nvm]
6.14.11

### PR DESCRIPTION
**Pull request by murgatroid99**
This fixes #1708. We actually ran into the same issue before in #1077 but I forgot when I implemented #1688.

### CODE REVIEW

**Comment by nicograef** [comment]
Hey @murgatroid99 , I ran into this issue today and could not find any solution to the issue (besides now finding this PR).
I checked the respective file `grpc-js/src/backoff-timeout.ts` and just removed all the ref/unref the logic. Without it it worked perfectly fine.

As I understand it, this code is made for running in a Node Environment and not inside a Browser. Am I correct?

So the first problem is the wrong type `NodeJS.Timer`

```typescript
// node_modules/@grpc/grpc-js/src/backoff-timeout.ts : 45

private timerId: NodeJS.Timer;
```

Which is wrong for the Browser Environment - it's `number` there.
Hence, the code fails in the Browser (if you don't remove the `.ref()` `.unref()` calls).

Anyways, cool that you fixed this already. For when is the release planned?

Besides, how does grpc-js generally handle the two environments?

Thanks!

**Comment by murgatroid99** [comment]
This library is made to work on Node, not browsers. The reason this timers thing is an issue is Electron: Electron fully supports the Node APIs, *except* that it uses browser timers instead of web timers. So we support Electron, but we have to make changes like this specifically for Electron.

This should release soon, once it gets a code review.

**Review by nicolasnoble — APPROVED** [review]
