### ISSUE TITLE
grpc-tools broken on mac OS?

### ISSUE THREAD

**Issue by mhoeger** [grpc/grpc-node#1484]
### Problem description
When I try to generate static code with grpc-tools, I run into this error:
```
dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
  Referenced from: /Users/mariehoeger/Documents/repos/ProjectBrasilia/src/Workers/NodeWorker/node_modules/grpc-tools/bin/protoc (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: ____chkstk_darwin
  Referenced from: /Users/mariehoeger/Documents/repos/ProjectBrasilia/src/Workers/NodeWorker/node_modules/grpc-tools/bin/protoc (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib
```

### Reproduction steps
Run command:
```
grpc_tools_node_protoc --js_out=import_style=commonjs,binary:./src/channels/cloudEvent/grpc/static_codegen/ --grpc_out=grpc_js:./src/channels/cloudEvent/grpc/static_codegen/ --plugin=protoc-gen-grpc=`which grpc_tools_node_protoc_plugin` cloudevent.proto
```
with grpc-tools@1.9.0 and mac OS High Sierra

### Environment
 - OS name, version and architecture: mac OS High Sierra (10.13.6)
 - Node version: v12.16.3
 - Node installation method: nvm
 - Package name and version: grpc-tools@1.9.0

### Additional context
I got this to work with grpc-tools@1.6.6. I landed on this version by looking at the last version that was here https://node-precompiled-binaries.grpc.io/

I also installed with `npm i grpc-tools`, not `npm i -g grpc-tools` and am running the command `grpc_tools_node_protoc` from an npm script

**Comment by murgatroid99** [comment]
This got delayed more than expected. I have published grpc-tools version 1.9.1 with a change that I think will fix this. Can you try that out?

**Comment by zaaxch** [comment]
I recently ran into the same problem, but it may just be my Mac version. I ran the same command as @mhoeger in the same context and received the same error. However, using version grpc-tools@1.6.6 worked without error. But I am unsure if I am losing certain functionality by using a lower verson.

### Environment

- OS name, version and architecture: mac OS Sierra (10.12.6)
- Node version: v14.7
- Node installation method: nvm
- Package name and version: grpc-tools@1.9.1

**Comment by hafizalfaza** [comment]
@zaaxch i also have the same issue using macOs High Sierra. Did you encounter any issue using grpc-tools@1.6.6 ? I consider using it until this library supports older macOS version

**Comment by zaaxch** [comment]
@hafizalfaza v1.6.6 worked just fine. However I have not read too much into the differences between versions to know if there are any, but I am assuming there are differences. Fortunately 1.6.6 worked for what I needed it to.

**Comment by josephharrington** [comment]
Hi @murgatroid99. Just a heads up that we had a couple folks run into this issue on grpc-tools@1.9.1 as well. One person was running macOS 10.13.6 and the other was on 10.12.6.

**Comment by eduardoramirez** [comment]
Hey, we're also seeing this issue on macos 10.13.6 and 10.14 using  grpc-tools@1.9.1

**Comment by mrdulin** [comment]
same. macOS 10.13.6 , grpc-tools@^1.9.1

**Comment by jinhuiWong** [comment]
same. macOS 10.13.6 , grpc-tools@^1.10.0

**Comment by Kupstas** [comment]
same. macOS 10.13.6 (17G65), "grpc-tools": "^1.11.1",
