### ISSUE TITLE
When updating to 1.12.1 from 1.11.3 there is Symbol not found error in Mac

### ISSUE THREAD

**Issue by aaltat** [grpc/grpc-node#2289]
When  running  grpc_tools_node_protoc command, there is error

> robotframework-playwright@14.3.0 grpc_tools_node_protoc
> grpc_tools_node_protoc --js_out=import_style=commonjs,binary:/Users/runner/work/robotframework-browser/robotframework-browser/node/playwright-wrapper/generated --grpc_out=grpc_js:/Users/runner/work/robotframework-browser/robotframework-browser/node/playwright-wrapper/generated --plugin=protoc-gen-grpc=/Users/runner/work/robotframework-browser/robotframework-browser/node_modules/.bin/grpc_tools_node_protoc_plugin -I ./protobuf protobuf/playwright.proto

```
dyld: Symbol not found: __ZTTNSt3__114basic_ifstreamIcNS_11char_traitsIcEEEE
  Referenced from: /Users/runner/work/robotframework-browser/robotframework-browser/node_modules/grpc-tools/bin/protoc (which was built for Mac OS X 12.0)
  Expected in: /usr/lib/libc++.1.dylib
 in /Users/runner/work/robotframework-browser/robotframework-browser/node_modules/grpc-tools/bin/protoc
/Users/runner/work/robotframework-browser/robotframework-browser/node_modules/grpc-tools/bin/protoc.js:41
    throw error;
    ^
```

Full error in https://github.com/MarketSquare/robotframework-browser/actions/runs/3622594524/jobs/6107495797

Again works with Windows and Linux, but not with Mac.

**Comment by murgatroid99** [comment]
I have published another fix in version 1.12.2. Please try it out.

**Comment by aaltat** [comment]
Looking about same in mobile
```

robotframework-playwright@14.3.0 grpc_tools_node_protoc
> grpc_tools_node_protoc --js_out=import_style=commonjs,binary:/Users/runner/work/robotframework-browser/robotframework-browser/node/playwright-wrapper/generated --grpc_out=grpc_js:/Users/runner/work/robotframework-browser/robotframework-browser/node/playwright-wrapper/generated --plugin=protoc-gen-grpc=/Users/runner/work/robotframework-browser/robotframework-browser/node_modules/.bin/grpc_tools_node_protoc_plugin -I ./protobuf protobuf/playwright.proto

dyld: Symbol not found: __ZTTNSt3__114basic_ifstreamIcNS_11char_traitsIcEEEE
  Referenced from: /Users/runner/work/robotframework-browser/robotframework-browser/node_modules/grpc-tools/bin/protoc (which was built for Mac OS X 12.0)
  Expected in: /usr/lib/libc++.1.dylib
 in /Users/runner/work/robotframework-browser/robotframework-browser/node_modules/grpc-tools/bin/protoc
/Users/runner/work/robotframework-browser/robotframework-browser/node_modules/grpc-tools/bin/protoc.js:41
    throw error

```

Full log in https://github.com/MarketSquare/robotframework-browser/actions/runs/3623390374/jobs/6109197685

**Comment by murgatroid99** [comment]
I think I fixed it in 1.12.3. Please try it out.

**Comment by aaltat** [comment]
Yes, the 1.12.3 does fix the problem. Thank you for support, I really appreciate it.
