### ISSUE TITLE
TypeError: Cannot read property '/service/method' of undefined

### ISSUE THREAD

**Issue by derolf** [grpc/grpc-node#363]
### Problem description
I am using a bare-bone `Client` and not a `ServiceClient`. When executing `makeUnaryRequest` (and or similar `makeXXXRequest`), I get the following error:

```
TypeError: Cannot read property '/<service>/<method>' of undefined
      at Client.makeUnaryRequest (/.../node_modules/grpc/src/client.js:457:39)
```
The offending line number varies with the actual version, however the offending line is:

`var method_name = this.$method_names[path];`

It happens to be that `$method_names` is defined in `makeClientConstructor`:

`ServiceClient.prototype.$method_names = {};`

So, `$method_names` is NOT defined for a bare-bone `Client`, which causes the crash.

### Reproduction

`package.json`:
```
{
  "dependencies": {
    "grpc": "^1.12.2"
  }
}
```

`index.js`:
```
const grpc = require("grpc");
const client = new grpc.Client("1.1.1.1", grpc.credentials.createInsecure());
client.makeUnaryRequest(
  "/service/method",
  null,
  null,
  {},
  null,
  null,
  () => {}
);
```

Run with node `index.js`.

Actual result:
```
TypeError: Cannot read property '/service/method' of undefined
    at Client.makeUnaryRequest (.../grpc-363/node_modules/grpc/src/client.js:457:39)
```

Expected result (error from running with grpc v1.10.1).
```
  var message = serialize(argument);
                ^

TypeError: serialize is not a function
    at Client.makeUnaryRequest (.../grpc-363/node_modules/grpc/src/client.js:544:17)
```

### Environment
- Broken in v1.11.X
- Works in v1.9 and v1.10

**Comment by nicolasnoble** [comment]
Please provide us with a full reproduction case.

**Comment by derolf** [comment]
I updated the problem statement with a "working" example.

**Comment by derolf** [comment]
Any update on this? This looks like a major regression because the generic client is broken now.

**Comment by murgatroid99** [comment]
I am looking into this now. I expect to have a fix out early next week.

**Comment by sangaman** [comment]
I am getting what appears to be the issue with v1.12.2. I only get it if I try to pass the method I want to call as a parameter, not if I call the method directly. The root cause is `$method_names` being undefined. Here's an example snippet:

```typescript
const lnrpcDescriptor: any = grpc.load(rpcprotopath);
this.lightning = new lnrpcDescriptor.lnrpc.Lightning(`${host}:${port}`, credentials);

this.lightning.getInfo({}, meta, callback); // this works

const getInfo = this.lightning.getInfo;
getInfo({}, meta, callback); // this throws TypeError: Cannot read property '/lnrpc.Lightning/GetInfo' of undefined
```

**Comment by derolf** [comment]
@sangaman your problem is unrelated. You are calling an unbound instance method.

**Comment by sangaman** [comment]
Ahhh thanks, I should have figured. Sorry for the tangent.

**Comment by murgatroid99** [comment]
I have published version 1.12.3 which includes #385, and that should fix the original issue.
