### ISSUE TITLE
Fails to build on clang 6.0.0

### ISSUE THREAD

**Issue by eatonphil** [grpc/grpc-node#267]
Error:

```
  COPY Release/libgrpc.a
  CXX(target) Release/obj.target/gpr/deps/grpc/src/core/lib/gpr/alloc.o
  CXX(target) Release/obj.target/gpr/deps/grpc/src/core/lib/gpr/arena.o
../deps/grpc/src/core/lib/gpr/arena.cc:86:42: error: static_cast from 'nullptr_t' to 'gpr_atm' (aka 'long') is not allowed
      if (!gpr_atm_rel_cas(&z->next_atm, static_cast<gpr_atm>(NULL),
```

Clang info:

```
$ clang --version
FreeBSD clang version 6.0.0 (tags/RELEASE_600/final 326565) (based on LLVM 6.0.0)
Target: x86_64-unknown-freebsd12.0
Thread model: posix
InstalledDir: /usr/bin
```

**Comment by nicolasnoble** [comment]
Filed grpc/grpc#15010 for this one.

**Comment by nicolasnoble** [comment]
I think this one got fixed eventually. Could you please confirm?

**Comment by bluecmd** [comment]
Running FreeBSD 11.2 BETA2, grpc HEAD and the same issue.

**Comment by thomasbuesser** [comment]
any news with this problem...?

**Comment by parliament718** [comment]
FreeBSD 11.1-RELEASE-p11
node v9.10.1

**Comment by murgatroid99** [comment]
The `grpc` package has been deprecated. We recommend using `@grpc/grpc-js` instead.
