### ISSUE TITLE
[question]: npm rebuild for electron@4.2.12

### ISSUE THREAD

**Issue by kittaakos** [grpc/grpc-node#1296]
Hi there, I am trying to use the latest `grpc` with Electron `4.2.12`.

I've noticed, others had similar [issues with Electron `4.0.4`](https://github.com/grpc/grpc-node/issues/762). Can someone please confirm whether I'm hitting the same ABI problem or not?

Steps to reproduce:
```
rm -rf grpc-test \
&& mkdir grpc-test \
&& cd grpc-test \
&& npm init -y \
&& npm i -S grpc \
&& npm i -D electron@4.2.12 npx \
&& npx electron --abi \
&& npm rebuild --target=4.2.12 --runtime=electron --dist-url=https://atom.io/download/electron \
&& ls -al ./node_modules/grpc/src/node/extension_binary/
```

Output of `ls`:
```
drwxr-xr-x 4 akos.kitta staff 128 Mar 10 11:59 .
drwxr-xr-x 3 akos.kitta staff  96 Mar 10 11:58 ..
drwxr-xr-x 3 akos.kitta staff  96 Mar 10 11:59 electron-v4.2-darwin-x64-unknown
drwxr-xr-x 3 akos.kitta staff  96 Mar 10 11:58 node-v64-darwin-x64-unknown
```

`node-v69-darwin-x64-unknown` is missing after the `npm rebuild`.

[This commit](https://github.com/cazfletch/blockchain-vscode-extension/commit/f9109856b15a24030e87170ea1c521ee280a37d4) inspired me to move `electron-v4.2-darwin-x64-unknown` to `node-v69-darwin-x64-unknown` as my Electron ABI version is `69`. I can confirm; it works at runtime but is it safe to do such a thing? Thank you!

**Comment by kittaakos** [comment]
@nicolasnoble, you [wrote](https://github.com/grpc/grpc-node/issues/762#issuecomment-480027506):

> We just published grpc-1.20.0-pre1 with hopefully electron 3.1 and 4.1 binaries. We're no longer going to produce 4.0 binaries due to the ABI instability issue on this branch.

I can understand you are not willing to produce binaries for 4.0, but should `grpc-node` work with electron 4.2.x after the `npm rebuild`? Thank you!

**Comment by kittaakos** [comment]
Even if I force ABI version `69`, I do get the correct version. This is what I've done:
```
npm rebuild --target=4.2.12 --runtime=electron --dist-url=https://atom.io/download/electron --abi=69
```

**Comment by murgatroid99** [comment]
The `electron-v4.2-darwin-x64-unknown` file is the correct one for Electron 4.2. Why do you think you need to change it?

**Comment by kittaakos** [comment]
When I start the electron app from the source, it works. When I bundle it up and start it from the terminal with `./electron/build/dist/mac/My\ App.app/Contents/MacOS/My\ App` I get an error:

```
Failed to start the backend application.
{ Error: Failed to load gRPC binary module because it was not installed for the current system
Expected directory: node-v69-darwin-x64-unknown
Found: [electron-v4.2-darwin-x64-unknown, node-v64-darwin-x64-unknown]
This problem can often be fixed by running "npm rebuild" on the current system
Original error: Cannot find module '/Users/akos.kitta/Desktop/my-app/electron/build/dist/mac/My App.app/Contents/Resources/app/node_modules/grpc/src/node/extension_binary/node-v69-darwin-x64-unknown/grpc_node.node'
    at Object.<anonymous> (/Users/akos.kitta/Desktop/my-app/electron/build/dist/mac/My App.app/Contents/Resources/app/node_modules/grpc/src/grpc_extension.js:53:17)
    at Object.<anonymous> (/Users/akos.kitta/Desktop/my-app/electron/build/dist/mac/My App.app/Contents/Resources/app/node_modules/grpc/src/grpc_extension.js:64:3)
    at Module._compile (internal/modules/cjs/loader.js:693:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/akos.kitta/Desktop/my-app/electron/build/dist/mac/My App.app/Contents/Resources/app/node_modules/grpc/src/client_interceptors.js:144:12) code: 'MODULE_NOT_FOUND' }
/Users/akos.kitta/Desktop/my-app/electron/build/dist/mac/My App.app/Contents/Resources/app/node_modules/@theia/core/lib/node/main.js:56
    throw reason;
```

**Comment by kittaakos** [comment]
> The `electron-v4.2-darwin-x64-unknown` file is the correct one for Electron 4.2

This helped a lot 👍 In our app we fork several processes from the electron main. So I logged `process.versions` in the main electron module and at the very first `grpc` require and I can see a difference.
```json
{
  "http_parser": "2.8.0",
  "node": "10.11.0",
  "v8": "6.9.427.31-electron.0",
  "uv": "1.23.0",
  "zlib": "1.2.11",
  "ares": "1.14.0",
  "modules": "69",
  "nghttp2": "1.33.0",
  "napi": "3",
  "openssl": "1.1.0",
  "electron": "4.2.12",
  "chrome": "69.0.3497.128",
  "icu": "62.2",
  "unicode": "11.0",
  "cldr": "33.1",
  "tz": "2019a"
}
```

```json
{
  "http_parser": "2.8.0",
  "node": "10.11.0",
  "v8": "6.9.427.31-electron.0",
  "uv": "1.23.0",
  "zlib": "1.2.11",
  "ares": "1.14.0",
  "modules": "69",
  "nghttp2": "1.33.0",
  "napi": "3",
  "openssl": "1.1.0",
  "icu": "62.2",
  "unicode": "11.0",
  "cldr": "33.1",
  "tz": "2019a"
}
````

```diff
11a12,13
>   "electron": "4.2.12",
>   "chrome": "69.0.3497.128",
```

If apply the following hack inside my bundled app, something like this, then it works:
```js
process.versions.electron = "4.2.12";
process.versions.chrome = "69.0.3497.128";
"use strict";

// ...

var grpc = require("grpc");
```

This is a problem inside our app. Thank you for your help, @murgatroid99!
